20GRPED.MVC1.A15.OneToMany/Controllers/CarroController.cs
using System.Linq;
using _20GRPED.MVC1.A15.OneToMany.Models;
using _20GRPED.MVC1.A15.OneToMany.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace _20GRPED.MVC1.A15.OneToMany.Controllers
{
    public class CarroController : Controller
    {
        private readonly ICarroService _carroService;

        public CarroController(
            ICarroService carroService)
        {
            _carroService = carroService;
        }
        // GET: Carro
        public ActionResult Index(string filtro = null)
        {
            ViewBag.Filtro = filtro;
            var carros = _carroService.GetAll(filtro);
            return View(carros);
        }

        // GET: Carro/Details/5
        public ActionResult Details(int id)
        {
            var carro = _carroService.GetById(id);
            return View(carro);
        }

        // GET: Carro/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Carro/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Carro carro)
        {
            try
            {
                _carroService.AddAsync(carro);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Carro/Edit/5
        public ActionResult Edit(int id)
        {
            var carro = _carroService.GetById(id);
            return View(carro);
        }

        // POST: Carro/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Carro carro)
        {
            try
            {
                _carroService.Update(id, carro);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Carro/Delete/5
        public ActionResult Delete(int id)
        {
            var carro = _carroService.GetById(id);
            return View(carro);
        }

        // POST: Carro/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                _carroService.Delete(id);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

20GRPED.MVC1.A15.OneToMany/Controllers/PessoaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _20GRPED.MVC1.A15.OneToMany.Models;
using _20GRPED.MVC1.A15.OneToMany.Repositories;
using _20GRPED.MVC1.A15.OneToMany.Repositories.Implementations;
using _20GRPED.MVC1.A15.OneToMany.Services;
using _20GRPED.MVC1.A15.OneToMany.Services.Implementations;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace _20GRPED.MVC1.A15.OneToMany.Controllers
{
    public class PessoaController : Controller
    {
        private readonly ICarroService _carroService;
        private readonly IPessoaService _pessoaService;

        public PessoaController(
            ICarroService carroService,
            IPessoaService pessoaService,
            CallCountScoped callCountScoped,
            CallCountSingleton callCountSingleton,
            CallCountTransient callCountTransient)
        {
            callCountScoped.Count++;
            callCountSingleton.Count++;
            callCountTransient.Count++;

            _carroService = carroService;
            _pessoaService = pessoaService;
        }

        // GET: Pessoa
        public async Task<ActionResult> Index(string filtro = null)
        {
            var pessoas = await _pessoaService.GetAllAsync();

            if (!string.IsNullOrWhiteSpace(filtro))
            {
                pessoas = pessoas.Where(x => x.Nome.Contains(filtro, StringComparison.OrdinalIgnoreCase));

                ViewBag.Filtro = filtro;
            }

            return View(pessoas);
        }

        // GET: Pessoa/Details/5
        public ActionResult Details(int id)
        {
            var pessoa = _pessoaService.GetByIdWithCarros(id);
            return View(pessoa);
        }

        // GET: Pessoa/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Pessoa/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(PessoaCarroCreateAggregateViewModel pessoaCarroCreateAggregateViewModel)
        {
            try
            {
                // TODO: Add insert logic here
                await _pessoaService.AddAsync(
                    new Pessoa { Nome = pessoaCarroCreateAggregateViewModel.NomePessoa },
                    new Carro
                    {
                        Modelo = pessoaCarroCreateAggregateViewModel.ModeloCarro,
                    });

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Pessoa/Edit/5
        public ActionResult Edit(int id)
        {
            var pessoa = _pessoaService.GetById(id);
            return View(pessoa);
        }

        // POST: Pessoa/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Pessoa pessoa)
        {
            try
            {
                // TODO: Add update logic here
                _pessoaService.Update(id, pessoa);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Pessoa/Delete/5
        public ActionResult Delete(int id)
        {
            var pessoa = _pessoaService.GetById(id);
            return View(pessoa);
        }

        // POST: Pessoa/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, Pessoa pessoa)
        {
            try
            {
                // TODO: Add delete logic here
                await _pessoaService.DeleteAsync(id);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public IActionResult TransferCar(int carroId, int pessoaId)
        {
            var carroUpdated = _carroService.GetById(carroId);
            if (carroUpdated == null)
                return View("CarroNaoEncontrado", pessoaId);

            carroUpdated.PessoaId = pessoaId;

            _carroService.Update(carroId, carroUpdated);

            return RedirectToAction(nameof(Details), new { id = pessoaId });
        }
    }
}

20GRPED.MVC1.A15.OneToMany/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - _20GRPED.MVC1.A15.OneToMany</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">_20GRPED.MVC1.A15.OneToMany</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pessoa" asp-action="Index">Pessoa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Carro" asp-action="Index">Carro</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - _20GRPED.MVC1.A15.OneToMany - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>